name: EnOcean YAML Manager
slug: enocean_yaml_manager
description: |
  Générez deux YAML EnOcean : un pour Home Assistant (auto)
  et un pour vos groupements lisibles (config). UI web simple.
version: 0.3.2
arch:
  - aarch64
  - amd64
  - armv7

# L’UI s’ouvre dans HA via Ingress (pas besoin d’exposer un port)
ingress: true                      # active Ingress
ingress_port: 9123                 # port *interne* écouté par l'app (uvicorn)
panel_title: "EnOcean YAML"        # titre dans le menu HA
panel_icon: "mdi:flash"            # icône (Material Design Icons)
# ingress_entry: "/"               # (optionnel) page d’entrée

startup: application
init: false
url: "https://github.com/maximedub/enocean_manager"

# PLUS BESOIN de webui/ports avec Ingress ; si tu veux aussi l’accès direct, tu peux
# réactiver :
# webui: "http://[HOST]:[PORT:9123]/"
# ports:
#   "9123/tcp": 9123

map:
  - config:rw

options:
  auto_output_path: /config/packages/enocean_auto.yaml
  auto_backup_path: /config/packages/enocean_auto.backup.yaml
  config_output_path: /config/packages/enocean_yaml_config.yaml
  config_backup_path: /config/packages/enocean_yaml_config.backup.yaml

schema:
  auto_output_path: str
  auto_backup_path: str
  config_output_path: str
  config_backup_path: str
