name: EnOcean YAML Manager
slug: enocean_yaml_manager
description: |
  Générez deux YAML EnOcean : un pour Home Assistant (auto)
  et un pour vos groupements lisibles (config). UI web simple.
version: 0.3.3
arch:
  - aarch64
  - amd64
  - armv7

# Ouverture dans HA (Ingress)
ingress: true
ingress_port: 9123
panel_title: "EnOcean YAML"
panel_icon: "mdi:flash"

startup: application
init: false
url: "https://github.com/maximedub/enocean_manager"

map:
  - config:rw

# ⚠️ Nouveaux chemins :
# - auto.yaml reste dans /config/packages/ (chargé par HA)
# - config.yaml sort de /packages/ pour éviter les erreurs de "domain inconnue"
# - backups en dehors de /packages/ pour ne pas être considérés comme des packages
options:
  auto_output_path: /config/packages/enocean_auto.yaml
  auto_backup_path: /config/enocean_manager/backups/enocean_auto.yaml.bak
  config_output_path: /config/enocean_yaml_config.yaml
  config_backup_path: /config/enocean_manager/backups/enocean_yaml_config.yaml.bak

schema:
  auto_output_path: str
  auto_backup_path: str
  config_output_path: str
  config_backup_path: str
