name: "EnOcean Manager"
version: "0.0.3a"
slug: "enocean_manager"
description: "Gérez l'appairage et la configuration de vos appareils EnOcean depuis Home Assistant"
arch:
  - amd64
  - armv7
  - aarch64
startup: application
boot: auto

ingress: true
ingress_port: 5000
panel_icon: "mdi:dolphin"
panel_title: "EnOcean Manager"

host_network: false
usb: true
uart: true

url: "https://github.com/maximedub/enocean_manager"

devices:
  - /dev/ttyUSB0

options: {}
schema: {}
