name: "EnOcean Manager"
slug: "enocean_manager"
version: "0.0.7b"
description: "Add-on Home Assistant pour gérer EnOcean à partir de profils EEP JSON."
url: "https://github.com/maximedub/enocean_manager"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
init: false
host_network: false
uart: true          # pour mapper auto les ports série
# apparmor: true    # (tu pourras ajouter un profil plus tard)
map:
  - config:rw
  - share:rw
  - addons:rw
options:
  serial_port: "/dev/ttyUSB0"
  json_dir: "/data/profile_json"
schema:
  serial_port: str
  json_dir: str
# Laisse "image" commenté pour forcer le build local :
# image: "maximedub/enocean_manager-{arch}"
